spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: plan.b.projectmanager@gmail.com
    password: nvor puox elyu uvii
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083
