spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter
## common configuration server implementation
  config:
    import: optional:config-server:http://localhost:8888
## application name
  application:
    name: api-gateway
## port that application running on
server:
  port: 8080
## eureka service registry url
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/