server:
  port: 8084
spring:
  application:
    name: workItem-service
  datasource:
    url: jdbc:mysql://localhost:3309/plan_b_workItem
    username: user
    password: password#2#2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka